name: Limpiar la cache de GitHub Actions
run: |
  npm cache clean --force

name: Despliegue de app web CI/CD Market House

on:
  push:
    branches:
      - main # Cambia 'main' por el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c贸digo fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Cambia a la versi贸n de Node.js que necesites

      - name: Instalar dependencias
        run: npm install # Cambia esto si utilizas otro sistema de gesti贸n de paquetes

      - name: Construir el sitio web
        run: npm run build # Cambia esto para ejecutar tu comando de construcci贸n

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./PRUEBA_MAPA # Cambia a la carpeta de tu sitio web generado
